name: webapp-github-action
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: node --version
      - run: npm --version
      - run: npm ci
      - run: npm test
      - run: zip -r webapp.zip *.js *.json
      - run: unzip -l webapp.zip
      - run: packer init custom-ami.pkr.hcl
      - run: packer validate custom-ami.pkr.hcl -var "DEV_USER_ID=${{env.DEV_AMI_ID}}" -var "DEMO_USER_ID"=${{env.DEMO_AMI_ID}}"